# Generated by Django 4.0.4 on 2022-04-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersupport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedmessage',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='telegram_user',
            new_name='t_user',
        ),
    ]
