# Generated by Django 4.0.4 on 2022-04-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersupport', '0003_userquestion_feedback_userquestion_helper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_role',
            field=models.CharField(default='ученик', max_length=255, verbose_name='Роль'),
        ),
    ]
