# Generated by Django 4.0.3 on 2022-04-19 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='UserID')),
                ('name', models.CharField(max_length=255, verbose_name='UserName')),
                ('user_role', models.CharField(max_length=255, verbose_name='Роль')),
                ('state', models.IntegerField(default=1, verbose_name='Работает?')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('chat_id', models.BigIntegerField(default=0, verbose_name='Чат пользователя')),
                ('chanel_id', models.BigIntegerField(default=0, verbose_name='Канал пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helper_id', models.BigIntegerField(default=0, verbose_name='ID Отвечающего')),
                ('question', models.CharField(max_length=5000, verbose_name='Вопрос')),
                ('history', models.CharField(max_length=10000, null=True, verbose_name='История вопроса')),
                ('state', models.CharField(default='Открытый вопрос', max_length=100, verbose_name='Состояние')),
                ('rate', models.CharField(max_length=1, null=True, verbose_name='Оценка')),
                ('feedback', models.CharField(max_length=5000, null=True)),
                ('mes_id', models.CharField(default='', max_length=20000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersupport.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kurators_chat', models.BigIntegerField(verbose_name='id вопроса у кураторов')),
                ('mentors_chat', models.BigIntegerField(verbose_name='id вопроса у наставников')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersupport.userquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
